### ISSUE TITLE
Failed to compile model on android, no reason given

### ISSUE THREAD

**Issue by distinctdan** [google-ai-edge/LiteRT#6999]
My model works on version 1.3.0, but I'm trying to upgrade to latest 2.1.4. However, it's failing to compile my model and won't show the reason why. I've tried on both CPU and GPU accelerators and gotten the same exception. The problem here is the model compiler doesn't return a reason why compilation failed, so I don't have any way to know what's wrong so that I can fix it. Can this please be changed to return the error reason from the native side?

Error log:
```
2026-04-18 06:05:09.175 21474-21474 litert                  com.cfa.kpa.aha.camera.test          I  [environment.cc:29] Creating LiteRT environment with options
2026-04-18 06:05:09.175 21474-21474 litert                  com.cfa.kpa.aha.camera.test          W  [auto_registration.cc:67] NPU accelerator could not be loaded and registered: kLiteRtStatusErrorInvalidArgument.
2026-04-18 06:05:09.175 21474-21474 litert                  com.cfa.kpa.aha.camera.test          I  [accelerator_registry.cc:52] RegisterAccelerator: ptr=0xb4000079ad1dbe50, name=GPU OpenCL
2026-04-18 06:05:09.175 21474-21474 litert                  com.cfa.kpa.aha.camera.test          I  [auto_registration.cc:137] Dynamically loaded GPU accelerator(libLiteRtOpenClAccelerator.so) registered.
2026-04-18 06:05:09.175 21474-21474 litert                  com.cfa.kpa.aha.camera.test          I  [accelerator_registry.cc:52] RegisterAccelerator: ptr=0xb4000079ad1dc160, name=CpuAccelerator
2026-04-18 06:05:09.175 21474-21474 litert                  com.cfa.kpa.aha.camera.test          I  [auto_registration.cc:168] CPU accelerator registered.
2026-04-18 06:05:09.179 21474-21474 litert                  com.cfa.kpa.aha.camera.test          I  [compiled_model.cc:467] Flatbuffer model initialized directly from incoming litert model.
2026-04-18 06:05:09.180 21474-21474 tflite                  com.cfa.kpa.aha.camera.test          I  Initialized TensorFlow Lite runtime.
2026-04-18 06:05:09.181 21474-21474 native                  com.cfa.kpa.aha.camera.test          E  E0000 00:00:1776506709.181687   21474 delegate_opencl.cc:624] Failed to open OpenCL library: UNKNOWN: Can not find OpenCL library on this device
                                                                                                    === Source Location Trace: ===
                                                                                                    third_party/ml_drift/cl/opencl_wrapper.cc:169
2026-04-18 06:05:09.181 21474-21474 litert                  com.cfa.kpa.aha.camera.test          E  [litert_compiled_model_jni.cc:771] Failed to create compiled model: Failed to compile model
2026-04-18 06:05:09.186 21474-21499 TestRunner              com.cfa.kpa.aha.camera.test          E  failed: defaultScanning(com.cfa.kpa.aha.camera.ScanningAccuracyTests)
2026-04-18 06:05:09.187 21474-21499 TestRunner              com.cfa.kpa.aha.camera.test          E  ----- begin exception -----
                                                                                                    com.google.ai.edge.litert.LiteRtException: Failed to compile model
                                                                                                    	at com.google.ai.edge.litert.CompiledModel.nativeCreateFromAsset(Native Method)
                                                                                                    	at com.google.ai.edge.litert.CompiledModel.access$nativeCreateFromAsset(Model.kt:56)
                                                                                                    	at com.google.ai.edge.litert.CompiledModel$Companion.nativeCreateFromAsset(Unknown Source:0)
                                                                                                    	at com.google.ai.edge.litert.CompiledModel$Companion.createFromAsset(Model.kt:529)
                                                                                                    	at com.google.ai.edge.litert.CompiledModel$Companion.createFromAsset$default(Model.kt:508)
                                                                                                    	at com.google.ai.edge.litert.CompiledModel$Companion.create(Model.kt:591)
                                                                                                    	at com.google.ai.edge.litert.CompiledModel$Companion.create$default(Model.kt:582)
                                                                                                    	at com.cfa.kpa.aha.camera.PanDetector.<init>(PanDetector.kt:61)
                                                                                                    	at com.cfa.kpa.aha.camera.ScanningAccuracyTests$defaultScanning$1$1.invokeSuspend(ScanningAccuracyTests.kt:65)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2026-04-18 06:05:09.187 21474-21499 TestRunner              com.cfa.kpa.aha.camera.test          E  ----- end exception -----
```

**Comment by sourcelite** [comment]
Hi @distinctdan, welcome here and thanks fr reporting this issue regarding the model compilation exception and the requesting to surface detailed native error reasons. I'm marking this as a bug for now, to help us investigate further compilation failure on version 2.1.4, could you provide us the following additional details ? - 

1. please can you share specific android device model and also os version you tried to run this tests ?
2. provide us the sharable code snippet ```PanDetector.kt:61``` showing us how youre configuring and init ```CompiledModel``` (specially regarding the hardware accelerators part)
3. please share model file you trying to compile, it will help us to reproduce the issue here locally.

We will need to take it further to first check the refactoring of JNI error propagation so that native strings are shown in the kotlin exception. Looking for this above information to help further and provide you support, thanks!

**Comment by distinctdan** [comment]
Thanks for the help, here are the details, but unfortunately our model is proprietary so I can't post it publicly. Would there be any way I could send it privately? 
1. Emulator Pixel Tablet Android 15.0 ("VanillaIceCream") | arm64 API 35
2. Here's the code, I've also tried with CPU accelerator and gotten the same error
```kotlin
    val model = CompiledModel.create(
        ctx.assets,
        "PanRecognizerModel.tflite",
        CompiledModel.Options(Accelerator.GPU),
    )
```

**Comment by aravindmurali22** [comment]
Hi @terryheo , following up on this thread, is there any update on this? Thanks!
