### ISSUE TITLE
How to add NPU support to  .literlm format model?

### ISSUE THREAD

**Issue by biaji** [google-ai-edge/LiteRT#7005]
I'm trying to perform AOT compilation of the gemma-4-e2b model following the reference [LiteRT_AOT_Compilation_Tutorial.ipynb](https://github.com/google-ai-edge/litert-samples/blob/main/compiled_model_api/colab/LiteRT_AOT_Compilation_Tutorial.ipynb), and I found that ```ai_edge_litert.aot``` only supports the TFLite format. 

It generate an error:
```
CMD: apply
MODEL: /tmp/tmppqlwtqm5
SOC_MANUFACTURER: Qualcomm
SOC_MODEL: SM8850

    __    _ __       ____  __
   / /   (_/ /____  / __ \/ /_
  / /   / / __/ _ \/ /_/ / __/
 / /___/ / /_/  __/ _, _/ /_
/_____/_/\__/\___/_/ |_|\__/

[LITERT_TOOLS:APPLY] Starting Load Model...
[LITERT_TOOLS:APPLY] Loading model from: /tmp/tmppqlwtqm5
ERROR: Model provided has model identifier 'RTLM', should be 'TFL3'

[LITERT_TOOLS:APPLY] Failed to load model from file.[LITERT_TOOLS:APPLY]        Failed
```

Should I manually convert the model from ```.safetensors``` to ONNX and then to ```.tflite```?

**Comment by sourcelite** [comment]
Thankyou for filing this issue, we will look into this and update here.

**Comment by biaji** [comment]
> Thankyou for filing this issue, we will look into this and update here.

 As .literlm is a container. May I just extract the orgin tflite model from it?

**Comment by sourcelite** [comment]
Hi @biaji, 

```log
As .literlm is a container. May I just extract the orgin tflite model from it?
```

sure. extracting the underlying .tflite file from it will help. And you can pass that extracted ```.tflite``` file directly to ai_edge_litert.aot tool for AOTcompilation.

For us, please help us understand your complete workflow, further compilation errors occurance, could you please clarify the initial source framework of your model (like Pytorch, JAX, etc) and share the steps, scripts used to generate initial ```.literlm```file ?

Thanks.

**Comment by biaji** [comment]
> Hi [@biaji](https://github.com/biaji),
> 
> ```
> As .literlm is a container. May I just extract the orgin tflite model from it?
> ```
> 
> sure. extracting the underlying .tflite file from it will help. And you can pass that extracted `.tflite` file directly to ai_edge_litert.aot tool for AOTcompilation.
> 
> For us, please help us understand your complete workflow, further compilation errors occurance, could you please clarify the initial source framework of your model (like Pytorch, JAX, etc) and share the steps, scripts used to generate initial `.literlm`file ?
> 
> Thanks.

@sourcelite 

Thanks a lot for your helpful response. Let me clarify my situation:

I’m a beginner working with large models, and my current goal is simply to explore acceleration on mobile devices (Qualcomm NPU) for running the gemma‑4‑e2b model. At the moment I’m experimenting with AOT compilation, though if JIT works that would also meet our needs.

I’ve successfully extracted the original .tflite files from the .litertlm container, but it seems there are multiple .tflite models embedded inside. 

```shell
-rw-rw-r--  1 0668000399 0668000399    9441244 Apr 29 17:15 tf_lite_audio_adapter.tflite
-rw-rw-r--  1 0668000399 0668000399   94052280 Apr 29 17:15 tf_lite_audio_encoder_hw.tflite
-rw-rw-r--  1 0668000399 0668000399  103811720 Apr 29 17:15 tf_lite_embedder.tflite
-rw-rw-r--  1 0668000399 0668000399       6772 Apr 29 17:15 tf_lite_end_of_audio.tflite
-rw-rw-r--  1 0668000399 0668000399       6772 Apr 29 17:15 tf_lite_end_of_vision.tflite
-rw-rw-r--  1 0668000399 0668000399   44332696 Apr 29 17:15 tf_lite_mtp_drafter.tflite
-rw-rw-r--  1 0668000399 0668000399 1284518392 Apr 29 17:15 tf_lite_per_layer_embedder.tflite
-rw-rw-r--  1 0668000399 0668000399  818275184 Apr 29 17:15 tf_lite_prefill_decode.tflite
-rw-rw-r--  1 0668000399 0668000399    4727112 Apr 29 17:15 tf_lite_vision_adapter.tflite
-rw-rw-r--  1 0668000399 0668000399  219090120 Apr 29 17:15 tf_lite_vision_encoder.tflite
```

My questions are:

- For AOT compilation, should each .tflite be compiled individually?
- After compilation, how should these be loaded back into LiteRT for execution?

Any guidance on the correct workflow would be greatly appreciated.

Thanks again for your support!

**Comment by sanoop-sadheerthan** [comment]
I'm also stuck at almost the same the same point.

Recently I have noticed in [litert-community/gemma-4-E2B-it-litert-lm](https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm) HF repo, I noticed addition of these two models for Qualcomm NPU execution
[gemma-4-E2B-it_qualcomm_qcs8275.litertlm](https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/main/gemma-4-E2B-it_qualcomm_qcs8275.litertlm) 
[gemma-4-E2B-it_qualcomm_sm8750.litertlm](https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/main/gemma-4-E2B-it_qualcomm_sm8750.litertlm)

How are they being generated, what is the flow to convert them?
Kindly help to understand this too.

Thank you for the support in advance!

**Comment by princeteng** [comment]
> > Hi [@biaji](https://github.com/biaji),
> > ```
> > As .literlm is a container. May I just extract the orgin tflite model from it?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sure. extracting the underlying .tflite file from it will help. And you can pass that extracted `.tflite` file directly to ai_edge_litert.aot tool for AOTcompilation.
> > For us, please help us understand your complete workflow, further compilation errors occurance, could you please clarify the initial source framework of your model (like Pytorch, JAX, etc) and share the steps, scripts used to generate initial `.literlm`file ?
> > Thanks.
> 
> [@sourcelite](https://github.com/sourcelite)
> 
> Thanks a lot for your helpful response. Let me clarify my situation:
> 
> I’m a beginner working with large models, and my current goal is simply to explore acceleration on mobile devices (Qualcomm NPU) for running the gemma‑4‑e2b model. At the moment I’m experimenting with AOT compilation, though if JIT works that would also meet our needs.
> 
> I’ve successfully extracted the original .tflite files from the .litertlm container, but it seems there are multiple .tflite models embedded inside.
> 
> -rw-rw-r--  1 0668000399 0668000399    9441244 Apr 29 17:15 tf_lite_audio_adapter.tflite
> -rw-rw-r--  1 0668000399 0668000399   94052280 Apr 29 17:15 tf_lite_audio_encoder_hw.tflite
> -rw-rw-r--  1 0668000399 0668000399  103811720 Apr 29 17:15 tf_lite_embedder.tflite
> -rw-rw-r--  1 0668000399 0668000399       6772 Apr 29 17:15 tf_lite_end_of_audio.tflite
> -rw-rw-r--  1 0668000399 0668000399       6772 Apr 29 17:15 tf_lite_end_of_vision.tflite
> -rw-rw-r--  1 0668000399 0668000399   44332696 Apr 29 17:15 tf_lite_mtp_drafter.tflite
> -rw-rw-r--  1 0668000399 0668000399 1284518392 Apr 29 17:15 tf_lite_per_layer_embedder.tflite
> -rw-rw-r--  1 0668000399 0668000399  818275184 Apr 29 17:15 tf_lite_prefill_decode.tflite
> -rw-rw-r--  1 0668000399 0668000399    4727112 Apr 29 17:15 tf_lite_vision_adapter.tflite
> -rw-rw-r--  1 0668000399 0668000399  219090120 Apr 29 17:15 tf_lite_vision_encoder.tflite
> My questions are:
> 
> * For AOT compilation, should each .tflite be compiled individually?
> * After compilation, how should these be loaded back into LiteRT for execution?
> 
> Any guidance on the correct workflow would be greatly appreciated.
> 
> Thanks again for your support!

I tried to perform AOT compilation on `tf_lite_prefill_decode.tflite`, then repackage it into litertlm. During inference, I found that the code in LiteRT-LM only supports `prefill_128`, while the official CPU/GPU builds of litertlm seem to exclusively use `prefill_256`.
https://github.com/google-ai-edge/LiteRT-LM/blob/60ae6962e0b6df5e0442b74464d4d56da89da362/runtime/executor/llm_litert_npu_compiled_model_executor.cc#L80

**Comment by biaji** [comment]
> 
> I tried to perform AOT compilation on `tf_lite_prefill_decode.tflite`, then repackage it into litertlm. During inference, I found that the code in LiteRT-LM only supports `prefill_128`, while the official CPU/GPU builds of litertlm seem to exclusively use `prefill_256`. https://github.com/google-ai-edge/LiteRT-LM/blob/60ae6962e0b6df5e0442b74464d4d56da89da362/runtime/executor/llm_litert_npu_compiled_model_executor.cc#L80


JIT has exactly the same error.

**Comment by princeteng** [comment]
> > I tried to perform AOT compilation on `tf_lite_prefill_decode.tflite`, then repackage it into litertlm. During inference, I found that the code in LiteRT-LM only supports `prefill_128`, while the official CPU/GPU builds of litertlm seem to exclusively use `prefill_256`. https://github.com/google-ai-edge/LiteRT-LM/blob/60ae6962e0b6df5e0442b74464d4d56da89da362/runtime/executor/llm_litert_npu_compiled_model_executor.cc#L80
> 
> JIT has exactly the same error.

The [litertlm](https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/main/gemma-4-E2B-it.litertlm) in huggingface has signature prefill_128, but the litertlm file downloaded from Edge Gallery (gemma4_2b_v09_obfus_fix_all_modalities_thinking.litertlm) does not seem to have the `prefill_128` signature. I am currently trying to perform AOT compilation with the LiteRT LM files from Hugging Face.

**Comment by biaji** [comment]
> > > I tried to perform AOT compilation on `tf_lite_prefill_decode.tflite`, then repackage it into litertlm. During inference, I found that the code in LiteRT-LM only supports `prefill_128`, while the official CPU/GPU builds of litertlm seem to exclusively use `prefill_256`. https://github.com/google-ai-edge/LiteRT-LM/blob/60ae6962e0b6df5e0442b74464d4d56da89da362/runtime/executor/llm_litert_npu_compiled_model_executor.cc#L80
> > 
> > 
> > JIT has exactly the same error.
> 
> The [litertlm](https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/main/gemma-4-E2B-it.litertlm) in huggingface has signature prefill_128, but the litertlm file downloaded from Edge Gallery (gemma4_2b_v09_obfus_fix_all_modalities_thinking.litertlm) does not seem to have the `prefill_128` signature. I am currently trying to perform AOT compilation with the LiteRT LM files from Hugging Face.

Any luck?  I stucked at "TF_LITE_AUX" not found in model.  😆

**Comment by mlnomadpy** [comment]
+1 — and a data point that extends this: even past the `RTLM`/`TFL3` barrier there's still no working generative-LLM → NPU path. Two routes, both dead-end on Tensor_G5:

- `litert-torch export-hf --aot_soc_model=Tensor_G5` (one-shot) on **gemma-3-1b-it** and **gemma-4** → fails with a bare `INTERNAL`.
- bypassing the format issue via `convert_to_tflite` (emits a valid multi-signature `TFL3`, prefill+decode) on **Qwen2.5-0.5B**, then `aot_compile(target=Tensor_G5)` → same `INTERNAL` (`compiler_plugin.cc:863`).

A **vision model compiles fine** in the same env, so it's specific to the generative graph. `ai-edge-litert*-nightly 2.2.0.dev20260529`. So both an official `.litertlm` → NPU recipe *and* a fix for the generative-graph compile look needed. Following.

**Comment by princeteng** [comment]
> > > > I tried to perform AOT compilation on `tf_lite_prefill_decode.tflite`, then repackage it into litertlm. During inference, I found that the code in LiteRT-LM only supports `prefill_128`, while the official CPU/GPU builds of litertlm seem to exclusively use `prefill_256`. https://github.com/google-ai-edge/LiteRT-LM/blob/60ae6962e0b6df5e0442b74464d4d56da89da362/runtime/executor/llm_litert_npu_compiled_model_executor.cc#L80
> > > 
> > > 
> > > JIT has exactly the same error.
> > 
> > 
> > The [litertlm](https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/main/gemma-4-E2B-it.litertlm) in huggingface has signature prefill_128, but the litertlm file downloaded from Edge Gallery (gemma4_2b_v09_obfus_fix_all_modalities_thinking.litertlm) does not seem to have the `prefill_128` signature. I am currently trying to perform AOT compilation with the LiteRT LM files from Hugging Face.
> 
> Any luck? I stucked at "TF_LITE_AUX" not found in model. 😆

It seems the new version of litert-torch supports exporting auxiliary.tflite (enable split_cache for Gemma4), but I haven't verified this personally yet.

**Comment by mlnomadpy** [comment]
> > > > > I tried to perform AOT compilation on `tf_lite_prefill_decode.tflite`, then repackage it into litertlm. During inference, I found that the code in LiteRT-LM only supports `prefill_128`, while the official CPU/GPU builds of litertlm seem to exclusively use `prefill_256`. https://github.com/google-ai-edge/LiteRT-LM/blob/60ae6962e0b6df5e0442b74464d4d56da89da362/runtime/executor/llm_litert_npu_compiled_model_executor.cc#L80
> > > > 
> > > > 
> > > > JIT has exactly the same error.
> > > 
> > > 
> > > The [litertlm](https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/main/gemma-4-E2B-it.litertlm) in huggingface has signature prefill_128, but the litertlm file downloaded from Edge Gallery (gemma4_2b_v09_obfus_fix_all_modalities_thinking.litertlm) does not seem to have the `prefill_128` signature. I am currently trying to perform AOT compilation with the LiteRT LM files from Hugging Face.
> > 
> > 
> > Any luck? I stucked at "TF_LITE_AUX" not found in model. 😆
> 
> It seems the new version of litert-torch supports exporting auxiliary.tflite (enable split_cache for Gemma4), but I haven't verified this personally yet.

this is from the beta version, presumably it is the last one with all features?

**Comment by aravindmurali22** [comment]
Hi @yuhuichen1015 , following up on this thread, is there any update on this? Thanks!
